apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
template:
  metadata:
    labels:
      name: busybox-pod
      command:
      - sh
      - "-c"
      - echo hello world && sleep 3600
